# Generated by Django 3.0.7 on 2020-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200629_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
