# Generated by Django 3.0.7 on 2020-06-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_answers_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
    ]
