# Generated by Django 3.0.7 on 2020-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200630_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.TextField(default='No name'),
        ),
    ]
