# Generated by Django 3.0.7 on 2020-07-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
